server:
  port: 8086
spring:
  application:
    name: mybatis-plugin-app
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
logging:
  level:
    root: info
    com.yicj.study.mybatis.repository.mapper: debug
# 关闭一级缓存
mybatis-plus:
  configuration:
    local-cache-scope: session
    cache-enabled: true

